# Generated by Django 2.0.3 on 2018-03-10 13:44

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('internet', 'internet'), ('electricity', 'electricity'), ('water', 'water'), ('gas', 'gas')], default=0, max_length=24, verbose_name='Bill type')),
                ('date_start', models.DateTimeField(verbose_name='start Date')),
                ('date_end', models.DateTimeField(verbose_name='end Date')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('date_create', models.DateTimeField(auto_now=True, verbose_name='Check in Date')),
                ('note', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('issued', 'issued'), ('confirm_paid', 'paid')], default='', max_length=24, verbose_name='Status')),
            ],
            options={
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='ParentProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='name')),
                ('type', models.CharField(choices=[('condo', 'condo'), ('hostel', 'hostel')], default='condo', max_length=24, verbose_name='Product structure')),
                ('structure', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[0, 0, 0], size=3, verbose_name='Structure')),
                ('floor', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[0, 0], size=2, verbose_name='Floor')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='Address')),
                ('furnish', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=[], size=None, verbose_name='Furnish')),
                ('note', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('deleted', 'deleted')], default='draft', max_length=64, verbose_name='Status')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('owner', models.ManyToManyField(related_name='parent_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_update'],
                'verbose_name': 'Parent Product',
                'verbose_name_plural': 'Parent Products',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='name')),
                ('type', models.CharField(choices=[('condo', 'condo'), ('single', 'single')], default='single', max_length=24, verbose_name='Product type')),
                ('structure', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[0, 0, 0], size=3, verbose_name='Structure')),
                ('floor', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[0, 0], size=2, verbose_name='Floor')),
                ('price', models.FloatField(default=0, verbose_name='Monthly Rent')),
                ('deposit', models.FloatField(default=0, verbose_name='deposit')),
                ('payment', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[0, 0], size=2, verbose_name='Payment ')),
                ('furnish', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=[], size=None, verbose_name='Furnish')),
                ('note', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('deleted', 'deleted')], default='draft', max_length=64, verbose_name='Status')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.ParentProduct', verbose_name='Parent')),
            ],
            options={
                'ordering': ['-date_update'],
                'verbose_name': 'Child Product',
                'verbose_name_plural': 'Child Products',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('slug', models.SlugField(max_length=32, verbose_name='Slug')),
                ('path', models.CharField(max_length=32, unique=True)),
                ('depth', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RentBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('internet', 'internet'), ('electricity', 'electricity'), ('water', 'water'), ('gas', 'gas'), ('rental', 'rental')], default='', max_length=24, verbose_name='Bill type')),
                ('date_start', models.DateTimeField(verbose_name='Check in Date')),
                ('date_end', models.DateTimeField(verbose_name='Check out Date')),
                ('date_create', models.DateTimeField(auto_now=True, verbose_name='Check in Date')),
                ('note', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('status', models.CharField(choices=[('issued', 'issued'), ('claim_paid', 'claim paid'), ('confirm_paid', 'confirm paid')], default='', max_length=24, verbose_name='bill status')),
                ('original_bill', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='shared_bills', to='product.GroupBill', verbose_name='Original Bill')),
            ],
            options={
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='RentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=0, verbose_name='Monthly Rent')),
                ('deposit', models.FloatField(blank=True, default=0, verbose_name='Deposit ')),
                ('payment', models.IntegerField(default=1, verbose_name='Billing cycle')),
                ('due_date', models.IntegerField(default=1, verbose_name='Due date')),
                ('date_contract_start', models.DateTimeField(verbose_name='Contract start')),
                ('date_contract_end', models.DateTimeField(verbose_name='Contract end')),
                ('date_checkin', models.DateTimeField(null=True, verbose_name='Check in Date')),
                ('date_checkout', models.DateTimeField(null=True, verbose_name='Check out Date')),
                ('date_create', models.DateTimeField(auto_now=True, verbose_name='Check in Date')),
                ('note', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('status', models.CharField(choices=[('ongoing', 'ongoing'), ('checked out', 'checked out'), ('deleted', 'deleted')], default='', max_length=24, verbose_name='order status')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='product.Product', verbose_name='Product')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Renter')),
            ],
            options={
                'ordering': ['-date_create'],
            },
        ),
        migrations.AddField(
            model_name='rentbill',
            name='rent_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='product.RentOrder', verbose_name='Rent Order'),
        ),
        migrations.AddField(
            model_name='rentbill',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL, verbose_name='renters'),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='region',
            field=models.ForeignKey(blank=True, db_column='region_path', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_products', to='product.Region', to_field='path', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='groupbill',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_bills', to='product.Product', verbose_name='Product'),
        ),
    ]
