# Generated by Django 2.0.3 on 2018-03-10 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_auto_20180310_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentproduct',
            name='owners',
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parentproduct',
            name='region',
            field=models.ForeignKey(db_column='region_path', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_products', to='product.Region', to_field='path', verbose_name='Region'),
        ),
    ]
