# Generated by Django 2.0.3 on 2018-03-12 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180311_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentproduct',
            name='address',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='parentproduct',
            name='owner',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='parent_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parentproduct',
            name='region',
            field=models.ForeignKey(db_column='region_path', default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='parent_products', to='product.Region', to_field='path', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='rentorder',
            name='renter',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Renter'),
        ),
    ]
