# Generated by Django 2.0.3 on 2018-03-27 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20180327_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentorder',
            name='renter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Renter'),
        ),
    ]
