# Generated by Django 2.0.3 on 2018-03-28 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20180327_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbill',
            name='status',
            field=models.CharField(choices=[('issued', 'issued'), ('confirm_paid', 'paid'), ('deleted', 'deleted')], default='', max_length=24, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='rentbill',
            name='date_create',
            field=models.DateTimeField(auto_now=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='rentbill',
            name='date_end',
            field=models.DateTimeField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='rentbill',
            name='date_start',
            field=models.DateTimeField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='rentbill',
            name='original_bill',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_bills', to='product.GroupBill', verbose_name='Original Bill'),
        ),
        migrations.AlterField(
            model_name='rentbill',
            name='status',
            field=models.CharField(choices=[('issued', 'issued'), ('claim_paid', 'claim paid'), ('confirm_paid', 'confirm paid'), ('deleted', 'deleted')], default='', max_length=24, verbose_name='bill status'),
        ),
    ]
