# Generated by Django 2.0.3 on 2018-03-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20180328_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentorder',
            old_name='payment',
            new_name='billing_cycle',
        ),
        migrations.RemoveField(
            model_name='rentorder',
            name='due_date',
        ),
        migrations.AddField(
            model_name='rentorder',
            name='due_day',
            field=models.IntegerField(default=1, verbose_name='Due day'),
        ),
    ]
