# Generated by Django 2.0.3 on 2018-03-30 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20180330_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentbill',
            name='renter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL, verbose_name='renters'),
        ),
    ]
