# Generated by Django 2.0.3 on 2018-04-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20180330_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentbill',
            name='renter',
        ),
    ]
