# Generated by Django 2.0.3 on 2018-04-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_rentbill_renter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentbill',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('issued', 'issued'), ('claim_paid', 'claim paid'), ('confirm_paid', 'confirm paid'), ('deleted', 'deleted')], default='', max_length=24, verbose_name='bill status'),
        ),
    ]
