# Generated by Django 2.0.3 on 2018-04-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20180412_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbill',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('issued', 'issued'), ('confirm_paid', 'paid'), ('deleted', 'deleted')], default='', max_length=24, verbose_name='Status'),
        ),
    ]
