# Generated by Django 2.0.3 on 2018-04-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20180412_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentorder',
            name='date_checkout',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check out Date'),
        ),
    ]
