# Generated by Django 2.0.3 on 2018-04-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20180413_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='upfront',
        ),
        migrations.AddField(
            model_name='product',
            name='pay_cycle',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('semimonthly', 'Semimonthly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannually', 'Semiannually'), ('annually', 'Annually')], default='monthly', max_length=16, verbose_name='Pay Cycle'),
        ),
    ]
