# Generated by Django 2.0.3 on 2018-05-02 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20180414_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('date_create', models.DateTimeField(auto_now=True, verbose_name='Create Date')),
                ('parentProduct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='product.ParentProduct', verbose_name='ParentProduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('date_create', models.DateTimeField(auto_now=True, verbose_name='Create Date')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='product.Product', verbose_name='Product')),
            ],
        ),
    ]
