# Generated by Django 2.0.3 on 2018-05-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_parentproductphoto_productphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentproductphoto',
            name='name',
            field=models.ImageField(upload_to='parent_product/%Y/%m/', verbose_name='name'),
        ),
    ]
