# Generated by Django 2.0.3 on 2018-05-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20180502_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentproductphoto',
            old_name='parentProduct',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='parentproductphoto',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productphoto',
            name='name',
        ),
        migrations.AddField(
            model_name='parentproductphoto',
            name='upload',
            field=models.ImageField(null=True, upload_to='parent_room/%Y/%m/', verbose_name='upload'),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='upload',
            field=models.ImageField(null=True, upload_to='room/%Y/%m/', verbose_name='upload'),
        ),
    ]
