# Generated by Django 2.0.3 on 2018-05-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20180502_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentproductphoto',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='productphoto',
            name='upload',
        ),
        migrations.AddField(
            model_name='parentproductphoto',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
    ]
