# Generated by Django 2.0.3 on 2018-05-12 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20180502_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentproductphoto',
            options={'ordering': ['-date_create']},
        ),
        migrations.AlterModelOptions(
            name='productphoto',
            options={'ordering': ['-date_create']},
        ),
    ]
