# Generated by Django 2.0.3 on 2018-05-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_parentproduct_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentproduct',
            name='cover_photo',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Cover Photo'),
        ),
    ]
