# Generated by Django 2.0.3 on 2018-05-22 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0027_auto_20180521_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentproductphoto',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ParentPhotos', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProductPhotos', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
