# Generated by Django 2.0.3 on 2018-05-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20180522_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentproduct',
            name='pay_cycle',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('semimonthly', 'Semimonthly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannually', 'Semiannually'), ('annually', 'Annually')], default='monthly', max_length=16, verbose_name='Pay Cycle'),
        ),
    ]
