# Generated by Django 2.0.3 on 2018-05-26 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_parentproduct_pay_cycle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Child Product', 'verbose_name_plural': 'Child Products'},
        ),
    ]
