# Generated by Django 2.0.3 on 2018-06-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_auto_20180526_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentproduct',
            options={'ordering': ['-date_create'], 'verbose_name': 'Parent Product', 'verbose_name_plural': 'Parent Products'},
        ),
    ]
