# Generated by Django 2.0.3 on 2018-06-05 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20180602_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentorder',
            name='renter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Renter'),
        ),
    ]
