# Generated by Django 2.0.3 on 2018-06-07 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20180605_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentorder',
            name='renter',
        ),
    ]
