# Generated by Django 2.0.3 on 2018-06-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_remove_rentorder_renter'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentorder',
            name='renter',
            field=models.CharField(blank=True, default='', max_length=24, verbose_name='Renter'),
        ),
    ]
