# Generated by Django 2.0.3 on 2018-06-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_rentorder_renter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentorder',
            options={'ordering': ['-date_contract_start']},
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='rentorder',
            name='status',
            field=models.CharField(choices=[('ongoing', 'ongoing'), ('checked_out', 'checked out'), ('deleted', 'deleted')], default='', max_length=24, verbose_name='order status'),
        ),
    ]
