# Generated by Django 2.0.3 on 2018-06-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_parentproduct_divide'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentproductphoto',
            name='type',
            field=models.CharField(default='public', max_length=16, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='type',
            field=models.CharField(default='public', max_length=16, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='parentproduct',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
