# Generated by Django 2.0.3 on 2018-07-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_auto_20180628_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentproduct',
            name='status',
            field=models.CharField(choices=[('default', 'default'), ('private', 'private'), ('public', 'public'), ('deleted', 'deleted'), ('pending_review', 'pending review')], default='', max_length=64, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable'), ('private', 'private'), ('public', 'public'), ('rented', 'rented'), ('deleted', 'deleted')], default='', max_length=64, verbose_name='Status'),
        ),
    ]
