# Generated by Django 2.0.3 on 2018-07-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_auto_20180717_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentproduct',
            name='type',
            field=models.CharField(choices=[('condo', 'condo'), ('hostel', 'hostel'), ('single', 'single')], default='condo', max_length=24, verbose_name='Product structure'),
        ),
    ]
