# Generated by Django 2.0.3 on 2018-07-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_auto_20180720_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentproduct',
            name='divide',
        ),
    ]
