# Generated by Django 2.0.3 on 2018-07-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_remove_parentproduct_divide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentproduct',
            name='status',
            field=models.CharField(choices=[('default', 'default'), ('private', 'private'), ('rejected', 'rejected'), ('public', 'public'), ('deleted', 'deleted'), ('pending_review', 'pending review')], default='', max_length=64, verbose_name='Status'),
        ),
    ]
