# Generated by Django 2.0.3 on 2018-03-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180310_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, default='---', max_length=32, verbose_name='role'),
        ),
    ]
