# Generated by Django 2.0.3 on 2018-06-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180312_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, default='-', max_length=32, verbose_name='role'),
        ),
    ]
